@startuml Class diagram
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0
top to bottom direction
skinparam linetype ortho


class ExpenseTracker {

    - expense_list : list
    - storage : StorageExpense
    
    - display_menu()
    - add_expense()
    - delete_expense()
    - view_expense()
    - show_total_spent()
    - get_expense(expense_id: int) : Expense

    + __init__()
    + run_app()

}

class Expense {
    
    {static} current_id: int = 1 
    - id: int
    - date: str
    - name: str
    - amount: float

    + __init__(date : str, name :string ,amount: float)
    + __str__() : str


}

class StorageExpense {
    
    - load_expenses()
    - save_expenses(expenses:list)
}

ExpenseTracker -> Expense
ExpenseTracker -> StorageExpense

@enduml